export const LOGIN_REQUEST = 'LOGIN_REQUEST';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';

export const GET_LOGIN_INFO_REQUEST = 'GET_LOGIN_INFO_REQUEST';

export const GET_VCODE_REQUEST = 'GET_VCODE_REQUEST';
